# Generated by cucumber-sinatra. (2013-08-27 14:37:39 +0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/backuper.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Backuper

class BackuperWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BackuperWorld.new
end
